version: '3.8'

services:
  sqlserverexpress:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserverexpress
    environment:
      SA_PASSWORD: "SchoolDb!Password278"
      MSSQL_PID: "Express"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
